### ISSUE TITLE
[Request] VPM support

### ISSUE THREAD

**Issue by Andazeus** [rurre/PumkinsAvatarTools#73]
Hello everyone,

as you have probably heard, VRC will enforce use of the Creator Companion starting next year.

It comes with the ability to create project templates that can automatically pull packages and insert them into new projects as well as automatically update packages.

Custom repositories and packages are supported as well, but in order to take advantage of most of the advanced automation features, packages need to be provided in the VPM format. Tooling and documentation on creating a VPM package is provided here:
https://github.com/vrchat-community/template-package

Since I consider Pumkin to be one of the most essential tools for avatar creation and management, I would love for it to be available as a custom VPM repo to be able to keep it included in my projects and updated automatically.

Are there any plans on looking into that functionality?

**Comment by rurre** [comment]
Not at the moment, but I'll look into it eventually.
Been kinda busy with other stuff.
________________________________
From: Andazeus ***@***.***>
Sent: Friday, November 18, 2022 11:25:08 AM
To: rurre/PumkinsAvatarTools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rurre/PumkinsAvatarTools] [Request] VPM support (Issue #73)


Hello everyone,

as you have probably heard, VRC will enforce use of the Creator Companion starting next year.

It comes with the ability to create project templates that can automatically pull packages and insert them into new projects as well as automatically update packages.

Custom repositories and packages are supported as well, but in order to take advantage of most of the advanced automation features, packages need to be provided in the VPM format. Tooling and documentation on creating a VPM package is provided here:
https://github.com/vrchat-community/template-package

Since I consider Pumkin to be one of the most essential tools for avatar creation and management, I would love for it to be available as a custom VPM repo to be able to keep it included in my projects and updated automatically.

Are there any plans on looking into that functionality?

**Comment by rurre** [comment]
VPM support was added a while ago. I forgot to go through these.
